Play around with tests

diff --git a/.docksal/commands/phpunit b/.docksal/commands/phpunit
--- a/.docksal/commands/phpunit
+++ b/.docksal/commands/phpunit
@@ -21,25 +21,40 @@ if [[ ! -f "$phpunit_xml_path" ]]; then
 fi
 
 phpunit_path="vendor/bin/phpunit"
+paraunit_path="vendor/bin/paraunit"
+
 if [[ ! -f "$phpunit_path" ]]; then
   echo "Could not find $phpunit_path"
   exit 1
 fi
 
-
 COVERAGE=false
+PARALLEL=true
 args=""
 while [ "$1" != "" ]; do
   case $1 in
-    --open-coverage )  COVERAGE=true
-                       ;;
-    *)                 args="$args $1"
-                       ;;
+    --open-coverage)
+      COVERAGE=true
+      ;;
+    -s | --force-sequential)
+      PARALLEL=false
+      ;;
+    *)
+      args="$args $1"
+      ;;
   esac
   shift
 done
 
+if $PARALLEL; then
+  if [[ ! -f "$paraunit_path" ]]; then
+    echo "Could not find $paraunit_path"
+    exit 1
+  fi
+fi
+
 timestamp=`date +%s`
+COVERAGE_FILE="$path/$DOCROOT/sites/simpletest/coverage/coverage-${timestamp}.cov"
 
 # fin exec "mkdir -p $path/$DOCROOT/sites/simpletest/coverage"
 
@@ -51,7 +66,11 @@ fi
 
 # Always create a dedicated coverage file for each test run. They get later
 # merged together into an HTML report
-fin exec "XDEBUG_MODE=coverage $path/${phpunit_path} -c $path ${args} $path/$DOCROOT/modules/custom --coverage-php $path/$DOCROOT/sites/simpletest/coverage/coverage-${timestamp}.cov"
+if $PARALLEL; then
+  fin exec "XDEBUG_MODE=coverage $path/${paraunit_path} coverage -c $path ${args} --php $COVERAGE_FILE"
+else
+  fin exec "XDEBUG_MODE=coverage $path/${phpunit_path} -c $path ${args} --coverage-php $COVERAGE_FILE"
+fi
 
 # Create the HTML report.
 fin exec "phpcov merge --html $path/$DOCROOT/sites/simpletest/coverage-html $path/$DOCROOT/sites/simpletest/coverage"
