HPC-10082: Try to fix tests by patching gin and getting rid of javascript console errors

diff --git a/.docksal/commands/phpunit b/.docksal/commands/phpunit
--- a/.docksal/commands/phpunit
+++ b/.docksal/commands/phpunit
@@ -23,14 +23,14 @@ fi
 phpunit_path="vendor/bin/phpunit"
 paraunit_path="vendor/bin/paraunit"
 
-if [[ ! -f "$phpunit_path" ]]; then
-  echo "Could not find $phpunit_path"
-  exit 1
-fi
+# if [[ ! -f "$phpunit_path" ]]; then
+#   echo "Could not find $phpunit_path"
+#   exit 1
+# fi
 
 COVERAGE=false
 CLEAR_LOGS=false
-PARALLEL=true
+PARALLEL=false
 OPEN_VNC=false
 args=""
 while [ "$1" != "" ]; do
@@ -54,12 +54,12 @@ while [ "$1" != "" ]; do
   shift
 done
 
-if $PARALLEL; then
-  if [[ ! -f "$paraunit_path" ]]; then
-    echo "Could not find $paraunit_path"
-    exit 1
-  fi
-fi
+# if $PARALLEL; then
+#   if [[ ! -f "$paraunit_path" ]]; then
+#     echo "Could not find $paraunit_path"
+#     exit 1
+#   fi
+# fi
 
 timestamp=`date +%s`
 COVERAGE_FILE="$path/$DOCROOT/sites/simpletest/coverage/coverage-${timestamp}.cov"
@@ -80,11 +80,12 @@ fi
 
 # Always create a dedicated coverage file for each test run. They get later
 # merged together into an HTML report
-if $PARALLEL; then
-  fin exec "XDEBUG_MODE=coverage $path/${paraunit_path} coverage -c $path ${args} --php $COVERAGE_FILE"
-else
-  fin exec "XDEBUG_MODE=coverage $path/${phpunit_path} -c $path ${args} --coverage-php $COVERAGE_FILE"
-fi
+# if $PARALLEL; then
+#   fin exec "XDEBUG_MODE=coverage $path/${paraunit_path} coverage -c $path ${args} --php $COVERAGE_FILE"
+# else
+#   fin exec "XDEBUG_MODE=coverage $path/${phpunit_path} -c $path ${args} --coverage-php $COVERAGE_FILE"
+# fi
+fin exec "XDEBUG_MODE=coverage $path/${phpunit_path} -c $path ${args} --coverage-php $COVERAGE_FILE"
 
 # Create the HTML report.
 fin exec "phpcov merge --html $path/$DOCROOT/sites/simpletest/coverage-html $path/$DOCROOT/sites/simpletest/coverage"
